
      </div>
    </div><!-- /.container -->

  </body>
  <script type="text/javascript" src="<?php echo $this->basePath; ?>js/jquery-3.3.1.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath; ?>js/bootstrap.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath; ?>js/datatables.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath; ?>js/beejeetest.js"></script>
</html>